name: CI

# Run the deployment only when code is committed to the branch.
on: pull_request

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
  lint-and-audit:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Set composer token
      run: composer config github-oauth.github.com ${{ secrets.PRIVATE_ACCESS_TOKEN }} 

    - name: Composer Install
      uses: ramsey/composer-install@v1

    - name: NPM Dependencies
      if: always()
      run: npm install

    - name: PHPCS check
      if: always()
      uses: chekalsky/phpcs-action@v1
      with:
        phpcs_bin_path: './vendor/bin/phpcs'

    - name: PHP Syntax Errors
      if: always()
      run: if find . -name "*.php" ! -path "./vendor/*" ! -path "./admin/bsf-core/*" -exec php -l {} \; | grep "Errors parsing"; then exit 1; fi

    - name: Lint JS
      if: always()
      run: npm run lint:js:fix

    - name: Commit ESLint fixes
      if: always()
      uses: EndBug/add-and-commit@v8.0.2
      with:
          add: 'src/*.js'
          default_author: github_actor
          message: 'Commit ESLint auto fixes'
          pathspec_error_handling: exitAtEnd
          push: true


